# -*- coding: utf-8 -*-
"""樂透.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McqlnCx7oEITiGPupHb4UkGVrPz0QRLQ
"""

import exlotto
print(lotto())